name: Publish to PyPI

on:
  push

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Package for PyPI
      run: |
        pip install --upgrade setuptools wheel
        python setup.py sdist bdist_wheel
    - name: Publish Package to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
